/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package unity.be.test;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.path.json.JsonPath;
import io.restassured.response.Response;
import org.testng.Assert;
import org.testng.annotations.*;
import static io.restassured.RestAssured.given;

public class AppTest {

    final String URL = "http://localhost:8080";

    @Test(dataProvider = "addPlayer")
    public void addPlayerTest(String json) {
        Response response = given().baseUri(URL).header("Content-Type", ContentType.JSON)
                .body(json)
                .when().post("/api/v1/player")
                .then().log().all().assertThat().statusCode(200).extract().response();

        Assert.assertEquals(response.asString(), "OK");
    }

    @Test(dataProvider = "getPlayer")
    public void getPlayerTest(String ign) {
        Response response = given().baseUri(URL).header("Content-Type", ContentType.JSON)
                .param("ign",ign)
                .when().get("/api/v1/player")
                .then().log().all().assertThat().statusCode(200).extract().response();

        JsonPath js = new JsonPath(response.asString());

        Assert.assertEquals(js.get("ign"), ign);
    }

    @DataProvider(name = "addPlayer")
    public Object[][] addPlayerDP() {
        return new Object[][] {
                {"{\"ign\":\"gph\"}"}
        };
    }

    @DataProvider(name = "getPlayer")
    public Object[][] getPlayerDP() {
        return new Object[][] {
                {"yoyoy123"}
        };
    }
}
